<?php

namespace common\models\c2\entity;

use common\models\c2\statics\InventoryExeState;
use cza\base\models\statics\EntityModelStatus;
use Yii;
use yii\validators\RequiredValidator;

/**
 * This is the model class for table "{{%order}}".
 *
 * @property string $id
 * @property string $user_id
 * @property string $code
 * @property string $label
 * @property string $production_date
 * @property string $delivery_date
 * @property string $created_by
 * @property string $updated_by
 * @property string $memo
 * @property integer $status
 * @property integer $position
 * @property integer $state
 * @property string $created_at
 * @property string $updated_at
 */
class OrderModel extends \cza\base\models\ActiveRecord
{

    public $items;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%order}}';
    }

    public function behaviors()
    {
        return \yii\helpers\ArrayHelper::merge(parent::behaviors(), [
            \yii\behaviors\BlameableBehavior::className(), // record created_by and updated_by
        ]);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'created_by', 'updated_by', 'position'], 'integer'],
            [['production_date', 'delivery_date', 'created_at', 'updated_at'], 'safe'],
            [['code', 'label', 'memo'], 'string', 'max' => 255],
            [['code',], 'required'],
            [['status', 'state'], 'integer', 'max' => 4],
            [['items'], 'validateItems'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app.c2', 'ID'),
            'user_id' => Yii::t('app.c2', 'User ID'),
            'code' => Yii::t('app.c2', 'Code'),
            'label' => Yii::t('app.c2', 'Label'),
            'production_date' => Yii::t('app.c2', 'Production Date'),
            'delivery_date' => Yii::t('app.c2', 'Delivery Date'),
            'created_by' => Yii::t('app.c2', 'Created By'),
            'updated_by' => Yii::t('app.c2', 'Updated By'),
            'memo' => Yii::t('app.c2', 'Memo'),
            'status' => Yii::t('app.c2', 'Status'),
            'position' => Yii::t('app.c2', 'Position'),
            'created_at' => Yii::t('app.c2', 'Created At'),
            'updated_at' => Yii::t('app.c2', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\c2\query\OrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\c2\query\OrderQuery(get_called_class());
    }

    /**
     * setup default values
     **/
    public function loadDefaultValues($skipIfSet = true)
    {
        parent::loadDefaultValues($skipIfSet);
        $this->state = InventoryExeState::INIT;
    }

    public function loadItems()
    {
        $this->items = $this->getOrderItems()->all();
    }

    public function getOrderItems()
    {
        return $this->hasMany(OrderItemModel::className(), ['order_id' => 'id']);
    }

    public function validateItems($attribute)
    {
        $requiredValidator = new RequiredValidator();
        foreach ($this->$attribute as $index => $row) {
            $error = null;
            $requiredValidator->validate($row['product_id'], $error);
            if (!empty($error)) {
                $key = $attribute . '[' . $index . '][product_id]';
                $this->addError($key, Yii::t('app.c2', '{attribute} can not be empty!', ['attribute' => Yii::t('app.c2', 'Product')]));
            }
            $requiredValidator->validate($row['product_pack_id'], $error);
            if (!empty($error)) {
                $key = $attribute . '[' . $index . '][product_pack_id]';
                $this->addError($key, Yii::t('app.c2', '{attribute} can not be empty!', ['attribute' => Yii::t('app.c2', 'Product')]));
            }
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if (!empty($this->items)) {
            foreach ($this->items as $item) {
                $attributes = [
                    // 'order_id' => $this->id,
                    'product_id' => isset($item['product_id']) ? $item['product_id'] : null,
                    'pieces' => isset($item['pieces']) ? $item['pieces'] : 0,
                    'quantity' => isset($item['quantity']) ? $item['quantity'] : 0,
                    'label' => isset($item['label']) ? $item['label'] : 0,
                    'product_pack_id' => isset($item['product_pack_id']) ? $item['product_pack_id'] : null,
                    'memo' => isset($item['memo']) ? $item['memo'] : "",
                ];
                if (isset($item['id']) && $item['id'] == '') {  // create new items
                    $itemModel = new OrderItemModel();
                    $itemModel->setAttributes($attributes);
                    $itemModel->link('owner', $this);
                } elseif (isset($item['id'])) {  // update itemes
                    $itemModel = OrderItemModel::findOne(['id' => $item['id']]);
                    if (!is_null($itemModel)) {
                        $itemModel->updateAttributes($attributes);
                    }
                }
            }
        }
    }

    public function isStateInit()
    {
        return ($this->state == InventoryExeState::INIT);
    }

    public function isStateFinish()
    {
        return ($this->state == InventoryExeState::FINISH);
    }

    public function isStateUntracked()
    {
        return ($this->state == InventoryExeState::UNTRACKED);
    }

    public function getCreator()
    {
        return $this->hasOne(\backend\models\c2\entity\rbac\BeUser::class, ['id' => 'created_by']);
    }

    public function getUpdater()
    {
        return $this->hasOne(\backend\models\c2\entity\rbac\BeUser::class, ['id' => 'updated_by']);
    }

    public function beforeDelete()
    {
        foreach ($this->orderItems as $item) {
            $item->delete();
        }
        return parent::beforeDelete();
    }

    public function getOrderItemOptions()
    {
        return $this->getOrderItems()->asArray()->all();
    }

    public function setStateToUntracked()
    {
        $this->loadItems();
        foreach ($this->items as $item) {
            $productPack = $item->productPack;
            if (!empty($productPack)) {
                if (!empty($productPack->inpack_id)) {
                    $attrs = [
                        'product_id' => $item->product_id,
                        'material_id' => $productPack->inpackMaterial->product_id,
                        'material_item_id' => $productPack->inpack_id,
                        'quantity' => $item->pieces,
                        'consumed_num' => $productPack->inpack_num,
                        'subtotal' => $productPack->inpack_num * $item->pieces,
                        // 'measure_id' => $item->measure_id,
                    ];
                    $model = new OrderItemConsumptionModel();
                    $model->setAttributes($attrs);
                    $model->link('owner', $this);
                }
                if (!empty($productPack->outpack_id)) {
                    $attrs = [
                        'product_id' => $item->product_id,
                        'material_id' => $productPack->inpackMaterial->product_id,
                        'material_item_id' => $productPack->outpack_id,
                        'quantity' => $item->pieces,
                        'consumed_num' => $productPack->outpack_num,
                        'subtotal' => $productPack->outpack_num * $item->pieces,
                        // 'measure_id' => $item->measure_id,
                    ];
                    $model = new OrderItemConsumptionModel();
                    $model->setAttributes($attrs);
                    $model->link('owner', $this);
                }
                $rs = $item->productMaterialRs;
                foreach ($rs as $r) {
                    $merNum = $item->pieces * $productPack->pre_num;
                    $attrs = [
                        'product_id' => $item->product_id,
                        'material_id' => $r->material_id,
                        'material_item_id' => $r->material_item_id,
                        'quantity' => $merNum,
                        'consumed_num' => $r->num,
                        'subtotal' => $r->num * $merNum,
                        // 'measure_id' => $item->measure_id,
                    ];
                    $model = new OrderItemConsumptionModel();
                    $model->setAttributes($attrs);
                    $model->link('owner', $this);
                }
            }
        }
        return $this->updateAttributes(['state' => InventoryExeState::UNTRACKED]);
    }

    public function setStateToFinish()
    {
        $items = $this->getOrderItemConsumption()->all();
        foreach ($items as $item) {
            $item->updateAttributes([
                'status' => EntityModelStatus::STATUS_INACTIVE
            ]);
        }
        return $this->updateAttributes(['state' => InventoryExeState::FINISH]);
    }

    public function getOrderItem($id)
    {
        $model = OrderItemModel::findOne($id);
        return $model->getMaterialOptions('id', 'label', ['withValue' => true]);
    }

    public function getUser()
    {
        return $this->hasOne(FeUserModel::className(), ['id' => 'user_id']);
    }

    public function getOrderItemConsumption()
    {
        return $this->hasMany(OrderItemConsumptionModel::className(), ['order_id' => 'id']);
    }

}
