<?php

namespace common\models\c2\entity;

use common\models\c2\statics\InventoryExeState;
use Yii;
use yii\validators\RequiredValidator;

/**
 * This is the model class for table "{{%order}}".
 *
 * @property string $id
 * @property string $user_id
 * @property string $order_no
 * @property string $production_date
 * @property string $delivery_date
 * @property string $created_by
 * @property string $updated_by
 * @property integer $state
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
class OrderModel extends \cza\base\models\ActiveRecord
{

    public $items;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%order}}';
    }

    public function behaviors()
    {
        return \yii\helpers\ArrayHelper::merge(parent::behaviors(), [
            \yii\behaviors\BlameableBehavior::className(), // record created_by and updated_by
        ]);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'order_no', 'created_by', 'updated_by', 'state'], 'integer'],
            [['production_date', 'delivery_date', 'created_at', 'updated_at'], 'safe'],
            [['status'], 'integer', 'max' => 4],
            [['items',], 'validateItems'],
            [['order_no',], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app.c2', 'ID'),
            'user_id' => Yii::t('app.c2', 'User ID'),
            'order_no' => Yii::t('app.c2', 'Order No'),
            'state' => Yii::t('app.c2', 'State'),
            'production_date' => Yii::t('app.c2', 'Production Date'),
            'delivery_date' => Yii::t('app.c2', 'Delivery Date'),
            'created_by' => Yii::t('app.c2', 'Created By'),
            'updated_by' => Yii::t('app.c2', 'Updated By'),
            'status' => Yii::t('app.c2', 'Status'),
            'created_at' => Yii::t('app.c2', 'Created At'),
            'updated_at' => Yii::t('app.c2', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\c2\query\OrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\c2\query\OrderQuery(get_called_class());
    }

    /**
     * setup default values
     **/
    public function loadDefaultValues($skipIfSet = true)
    {
        parent::loadDefaultValues($skipIfSet);
        $this->state = InventoryExeState::INIT;
    }

    public function loadItems()
    {
        $this->items = $this->getOrderItems()->all();
    }

    public function getOrderItems()
    {
        return $this->hasMany(OrderItemModel::className(), ['order_id' => 'id']);
    }

    public function validateItems($attribute)
    {
        $requiredValidator = new RequiredValidator();
        foreach ($this->$attribute as $index => $row) {
            $error = null;
            $requiredValidator->validate($row['product_id'], $error);
            if (!empty($error)) {
                $key = $attribute . '[' . $index . '][product_id]';
                $this->addError($key, Yii::t('app.c2', '{attribute} can not be empty!', ['attribute' => Yii::t('app.c2', 'Product')]));
            }
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if (!empty($this->items)) {
            foreach ($this->items as $item) {
                $attributes = [
                    'order_id' => $this->id,
                    'product_id' => isset($item['product_id']) ? $item['product_id'] : null,
                    'num' => isset($item['num']) ? $item['num'] : 0,
                    'pieces' => isset($item['pieces']) ? $item['pieces'] : 0,
                    'packing' => isset($item['packing']) ? $item['packing'] : "",
                    'size' => isset($item['size']) ? $item['size'] : "",
                    'gross_weight' => isset($item['gross_weight']) ? $item['gross_weight'] : "",
                    'net_weight' => isset($item['net_weight']) ? $item['net_weight'] : "",
                    'memo' => isset($item['memo']) ? $item['memo'] : "",
                ];
                if (isset($item['id']) && $item['id'] == 0) {  // create new items
                    $itemModel = new OrderItemModel();
                    $itemModel->setAttributes($attributes);
                    $itemModel->link('owner', $this);
                } elseif (isset($item['id'])) {  // update itemes
                    $itemModel = OrderItemModel::findOne(['id' => $item['id']]);
                    if (!is_null($itemModel)) {
                        $itemModel->updateAttributes($attributes);
                    }
                }
            }
        }
    }

    public function isStateInit()
    {
        return ($this->state == InventoryExeState::INIT);
    }

    public function isStateFinish()
    {
        return ($this->state == InventoryExeState::FINISH);
    }

    public function isStateUntracked()
    {
        return ($this->state == InventoryExeState::UNTRACKED);
    }

    public function getCreator()
    {
        return $this->hasOne(\backend\models\c2\entity\rbac\BeUser::class, ['id' => 'created_by']);
    }

    public function getUpdater()
    {
        return $this->hasOne(\backend\models\c2\entity\rbac\BeUser::class, ['id' => 'updated_by']);
    }

    public function beforeDelete()
    {
        foreach ($this->orderItems as $item) {
            $item->delete();
        }
        return parent::beforeDelete();
    }

    public function getOrderItemOptions()
    {
        return $this->getOrderItems()->asArray()->all();
    }

    public function setStateToFinish()
    {
        $this->loadItems();
        foreach ($this->items as $item) {
            $rs = $item->productMaterialRs;
            foreach ($rs as $r) {
                $attrs = [
                    'product_id' => $item->product_id,
                    'material_id' => $r->material_id,
                    'material_item_id' => $r->material_item_id,
                    'quantity' => $item->num,
                    'consumed_num' => $r->num,
                    'subtotal' => $r->num * $item->num,
                    // 'measure_id' => $item->measure_id,
                ];
                $model = new OrderItemConsumptionModel();
                $model->setAttributes($attrs);
                $model->link('owner', $this);
            }
        }
        return $this->updateAttributes(['state' => InventoryExeState::UNTRACKED]);
    }

    public function getOrderItem($id)
    {
        $model = OrderItemModel::findOne($id);
        return $model->getMaterialOptions('id', 'label', ['withValue' => true]);
    }

    public function getUser()
    {
        return $this->hasOne(FeUserModel::className(), ['id' => 'user_id']);
    }

}
