<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Refresh' => '刷新',
    'Calculate' => '计算',
    'Material' => '材料',
    'User business' => '客户',
    'User employee' => '员工',
    'Order' => '订单',
    'Size' => '尺寸',
    'Gross weight' => '毛重',
    'Net weight' => '净重',
    'Packing' => '包装',
    'Packing method' => '包装方式',
    'Order No' => '订单编号',
    'Delivery Date' => '出货日期',
    'Production Date' => '排产日期',
    'Num {s1}' => '(数量:{s1})',
    'Order Models' => '销售订单',
    'Order Model' => '销售订单',
    'Contact phone' => '联系电话',
    'Department' => '部门',
    'Arrival Date' => '收货日期',
    'Receive company' => '收货单位',
    'Untracked' => '待跟进',
    'Commit' => '实核',
    'Commit note' => '采购单进仓核算',
    'Untracked Notes' => '待跟进订单',
    'Stock num' => '库存',
    'Stock quantity' => '库存占有数量',
    'Actual quantity' => '生产占有数量',
    'Multiple stock' => '该产品已存在库存',
    'Receipt note code' => '采购单编号',
    'Delivery note code' => '出仓单编号',
    'Warehouse Receipt Commit Item Models' => '采购记录',
    'Warehouse Delivery Commit Item Models' => '出库记录',
    'EsConsumption' => '消耗预算',
    'Consumed Num' => '消耗量',
    'Stock exception' => '欠料情况',
    'Enough' => '充足',
    'Not enough' => '不足',
    'Order Item Consumption Models' => '订单用料情况',
    'OutPack size' => '外箱尺寸',
    'InPack size' => '内箱尺寸',
    'PrePrice' => '单价',
    'Finish order' => '完成订单',
    'Are you sure Finish order' => '你确定完成订单吗',
    'Product Models' => '产品列表',
    'Per Package Product Number' => '填写该包装方式的产品数',
    'Name' => '名称',
    'Label' => '标签',
    'Gross Weight' => '毛重',
    'Net Weight' => '净重',
    'Product ID' => '产品名称',
    'Number' => '数量',
    '' => '',
];

