<?php

namespace backend\modules\Database\modules\Product\widgets;

use backend\models\c2\form\EavSkuForm;
use Yii;
use cza\base\widgets\ui\common\part\EntityDetail as DetailWidget;

/**
 * Entity Detail Widget
 *
 * @author Ben Bi <ben@cciza.com>
 * @link http://www.cciza.com/
 * @copyright 2014-2016 CCIZA Software LLC
 * @license
 */
class EntityDetail extends DetailWidget
{
    public $withTranslationTabs = false;

    public $withProfileTab = false;
    public $withSkuTab = false;

    public function getTabItems()
    {
        $items = [];
        if ($this->withSkuTab) {
            $items[] = $this->getSkuTab();
        }

        if ($this->withBaseInfoTab) {
            $items[] = [
                'label' => Yii::t('app.c2', 'Base Information'),
                'content' => $this->controller->renderPartial('_form', ['model' => $this->model,]),
                'active' => true,
            ];
        }

        $items[] = [
            'label' => '<i class="fa fa-th"></i> ' . $this->tabTitle,
            'onlyLabel' => true,
            'headerOptions' => [
                'class' => 'pull-left header',
            ],
        ];

        return $items; // TODO: Change the autogenerated stub
    }

    public function getSkuTab()
    {
        if (!isset($this->_tabs['SKU_TAB'])) {
            if (!$this->model->isNewRecord) {
                $this->_tabs['SKU_TAB'] = [
                    'label' => Yii::t('app.c2', 'Product Sku Management'),
                    'content' => $this->controller->renderPartial('/default/_sku_form', ['model' => new EavSkuForm(['entityModel' => $this->model])]),
                    // 'content' => $this->controller->renderPartial('/default/_material_form', ['model' => $this->model->loadItems()]),
                    'enable' => true
                ];
            } else {
                $this->_tabs['SKU_TAB'] = [
                    'label' => Yii::t('app.c2', 'Product Sku Management'),
                    'content' => "",
                    'enable' => false,
                ];
            }
        }
        return $this->_tabs['SKU_TAB'];
    }

}