<?php

namespace common\behaviors;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use cza\base\models\ActiveRecord;
/**
 * @Author cch
 */
class SnapshotAppBehavior extends yii\base\Behavior {

    public $snapshotEntityClass;
    public $primaryKey;
    public $snapshotValues = [];
    public $snapshotFunctions = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function events() {
        return [
            ActiveRecord::EVENT_AFTER_FIND => 'getValueWithSnapshot',
        ];
    }

    public function getValueWithSnapshot()
    {
        if (isset($this->owner->state)){
            $snapsDatas = $this->owner->getSnapshot($this->owner->state);
        }else{
            $snapsDatas = $this->owner->getSnapshot();
        }
        foreach ($this->owner as $key=>$value){
            if ($key!='id'){
                if (isset($snapsDatas[$key])){
                    $this->owner[$key] = $snapsDatas[$key];
                }
            }
        }
        foreach ($this->snapshotValues as $key => $value){
            if (isset($this->owner[$key]) && isset($snapsDatas[$value])){
                $this->owner[$key] = $snapsDatas[$value];
            }
        }

        foreach ($this->snapshotFunctions as $key => $value){
            if (isset($this->owner->$key) && isset($snapsDatas[$value])){
                $this->owner->$key = $snapsDatas[$value];
            }
        }

    }



}
